### ISSUE TITLE
-Windows 11(Version 23H2 Build 22631.4037)で初めてショートカットを開こうとすると「動作を停止しました」と出ます。X4はすべてのDLC導入済です。(3.1.8)

### ISSUE THREAD

**Issue by GRIMROCKJPN** [Ocelot1210/X4_ComplexCalculator#188]
# Describe the bug

# To Reproduce
1. Open shortcut Link”X4_ComplexCalculator.exe”
2. Click on 'Seculity alert' Open button
3. See error

# Expected behavior

# Screenshots

# Execution environment
- OS: [e.g. Windows 11 Ver.23H2, Build:22631.4037]
- Language ja-JP
- App version latest 3.1.8
- Version of X4. 7.10(538538)
- Installed mods / DLCs.
    All DLCs
   Vanilla No Mods
# Additional context
Add any other context about the problem here. [e.g. X4_ComplexCalculator_CrashReport.txt]

**Comment by Ocelot1210** [comment]
7zip を使用して X4_ComplexCalculator.zip を解凍してみてください

それでも解決しない場合、お手数ですが以下の手順でイベントビューアーのログを送付お願いします


1. [こちら](https://win11lab.info/win11-event-viewer/) のサイトを参考に、イベントビューアーを起動してください
2. Windows ログ → Application の順に選択してください
3. X4 ステーション計算機が動作を停止した時刻付近に、計算機のログがあると思われますので、そのログの内容をご連絡お願いします

**Comment by GRIMROCKJPN** [comment]
7Zipで解凍して同じエラーが発生しました。以下にアプリケーションエラーのログを添付致します。

障害が発生しているアプリケーション名: X4_ComplexCalculator.exe、バージョン: 3.1.8.0、タイム スタンプ: 0x66470000
障害が発生しているモジュール名: KERNELBASE.dll、バージョン: 10.0.22621.3958、タイム スタンプ: 0xfbc3a4f6
例外コード: 0xe0434352
障害オフセット: 0x000000000005fabc
障害が発生しているプロセス ID: 0x0x44
障害が発生しているアプリケーションの開始時刻: 0x0x1DAF7F16F05D92B
障害が発生しているアプリケーション パス: H:\X4_ComplexCalculator\bin\X4_ComplexCalculator.exe
障害が発生しているモジュール パス: C:\WINDOWS\System32\KERNELBASE.dll
レポート ID: 9d7626fb-d599-4ee0-b613-370d1c2aea92
障害が発生しているパッケージの完全な名前: 
障害が発生しているパッケージに関連するアプリケーション ID: 

.NET Runtimeも同時刻でエラーログを吐いてるのですが必要でしょうか？念のため添付しておきます。

Application: X4_ComplexCalculator.exe
CoreCLR Version: 8.0.624.26715
.NET Version: 8.0.6
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Windows.Markup.XamlParseException: 指定されたバインディング制約に一致する型 'X4_ComplexCalculator.Main.MainWindow' のコンストラクターの呼び出しで例外がスローされました。
 ---> System.TypeInitializationException: The type initializer for 'X4_ComplexCalculator.Common.Configuration' threw an exception.
 ---> System.UnauthorizedAccessException: Access to the path 'C:\WINDOWS\system32\App.config.json' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at X4_ComplexCalculator.Common.Configuration.FixSettingFile(String path) in D:\a\X4_ComplexCalculator\X4_ComplexCalculator\X4_ComplexCalculator\Common\Configuration.cs:line 184
   at X4_ComplexCalculator.Common.Configuration..ctor(String path) in D:\a\X4_ComplexCalculator\X4_ComplexCalculator\X4_ComplexCalculator\Common\Configuration.cs:line 106
   at X4_ComplexCalculator.Common.Configuration..cctor() in D:\a\X4_ComplexCalculator\X4_ComplexCalculator\X4_ComplexCalculator\Common\Configuration.cs:line 21
   --- End of inner exception stack trace ---
   at X4_ComplexCalculator.Common.Configuration.get_Instance() in D:\a\X4_ComplexCalculator\X4_ComplexCalculator\X4_ComplexCalculator\Common\Configuration.cs:line 21
   at X4_ComplexCalculator.Main.LanguagesManager..ctor() in D:\a\X4_ComplexCalculator\X4_ComplexCalculator\X4_ComplexCalculator\Main\LanguagesManager.cs:line 44
   at X4_ComplexCalculator.Main.MainWindowViewModel..ctor(ILocalizedMessageBox messageBox) in D:\a\X4_ComplexCalculator\X4_ComplexCalculator\X4_ComplexCalculator\Main\MainWindowViewModel.cs:line 52
   at X4_ComplexCalculator.Main.MainWindow..ctor() in D:\a\X4_ComplexCalculator\X4_ComplexCalculator\X4_ComplexCalculator\Main\MainWindow.xaml.cs:line 15
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at X4_ComplexCalculator.App.Main()

**Comment by GRIMROCKJPN** [comment]
ショートカットではなくexeを直接開き、X4のインストールフォルダを移動して別ドライブにしたら何故か開けました。フォルダ名に空白が入ってたりすると駄目だったのでしょうか？原因は不明ですが解決しましたのでご報告まで。お騒がせしました。
