### ISSUE TITLE
Data export failed

### ISSUE THREAD

**Issue by mycumycu** [Ocelot1210/X4_ComplexCalculator#85]
Hi,

data exporter throws an error with ComplexCalculator v3.0.3. and X4 v4.0 HF3 (en version).

```
Sorry, Data export failed.
Please report the following content to the developer.

1. Selected language.
2. Crash report file. (this file)
3. Version of X4.


----------------------------------------------------------------------
Exception information
----------------------------------------------------------------------
■ Type :
System.Data.SQLite.SQLiteException

■ Message :
constraint failed
UNIQUE constraint failed: Ware.WareID

■ StackTrace :
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 554
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 443
   at X4_DataExporterWPF.Export.WareExporter.Export(IDbConnection connection, IProgress`1 progress)
   at X4_DataExporterWPF.DataExportWindow.DataExportModel.Export(IProgress`1 progress, IProgress`1 progressSub, String inDirPath, String outFilePath, LangComboboxItem language, Window owner)





----------------------------------------------------------------------
Installed mods
----------------------------------------------------------------------
ID	Name	Author	Version	Date	Enabled	Save
ws_1673263604	No Fog	alexalsp	007	2021-03-20		false
ws_2412422230	Starbright: Variable sector sunlight levels	Allectus	121	2021-03-15		false
ws_2437198154	Subsystem Targeting Orders	Allectus	351	2021-05-22		false
ws_2459574093	Urgent Orders	Allectus	121	2021-05-22		false
ws_2484521478	Wing Hotkeys	Allectus	100	2021-05-11		false
ApologizeForAttack	ApologizeForAttack	iforgotmysocks	021	2019-12-24	true	false
ws_2411366357	Neutral Engine Tints	Axeface	100	2021-03-01		0
ws_2083714551	Paintjobs Galore!	Axeface	110	2020-09-19		0
betterScanColors	Better Scan Colors	FlynTie	1.1	2018-07-12	1	0
ws_1700645587	Better Kill Credit	Mysterial (mysterial@mysterial.net)	131	2021-04-19		false
ws_2056100433	Better piracy	alberto-rota	1300	2020-05-29		0
CrystalClear	Crexit	Moonrat	003	2020-04-25		0
ws_2302661654	Custom Game Editor (Creative)	Retrov1si0n	330	2020-11-29		0
DeadAirAITweaks	DeadAir AI Tweaks	DeadAir	102	2021-03-03	0	0
DeadAirDWS	DeadAir Dynamic Wars	DeadAir	133	2021-03-16	1	0
DeadAirGate	DeadAir Gate	DeadAir	001	2021-03-03	1	1
ego_dlc_split	Split Vendetta	Egosoft GmbH	100	2020-03-31	1	1
ego_dlc_terran	Cradle of Humanity	Egosoft GmbH	100	2021-03-16	1	1
ws_2329127940	Encounters	Moonrat	110	2020-12-21		0
EnhancedSatellites	EnhancedSatellites	MrWaxton	100	2020-1-3		0
ws_2326368267	Escape Pod	strayhound	110	2021-02-12		0
Event_driven_news	Event Driven News	mrjonesandme	103	2020-04-25		0
ExtendedConversationMenu	Extended Conversation Menu	iforgotmysocks	020	2019-12-29	true	false
ws_2074838459	Sector Explorer	Assailer	127	2021-05-20		0
ws_2458720435	Sector Patrol	Assailer	105	2021-04-19		0
ws_2061697157	GEM FX	Ganossa	113	2020-04-28		0
GettingPaid	GettingPaid	iforgotmysocks	100	2018-12-12		0
ImprovedRepairLaser	ImprovedRepairLaser	iforgotmysocks	010	2018-12-01		0
SN_increase_first_person_speed	Increase First Person Speed		101	2018-12-4	true	false
InfoCenter	Info Center	Forleyor	282	2019-04-06	1	0
ws_2046100040	Cheat Menu	iseeu0	141	2021-05-08		0
j.h_PatrolArea	Patrol Area	j.h	001	2018-12-28		false
JP_SatelliteDropper	JP_SatelliteDropper	JanPanthera	120	2021-01-10	1	0
ws_2440309187	Hazard Rework	draeath	101	2021-04-01		false
kuerteeAlternativesToDeath	kuertee: Alternatives to death	kuertee	206	2021-05-29	1	false
kuerteeCrimeHasConsequences	kuertee: Crime has consequences	kuertee	207	2021-05-29	1	false
kuerteeFriendlyFireTweaks	kuertee: Friendly fire tweaks	kuertee	101	2021-05-29	1	false
kuertee_hacking_outcomes	kuertee: Hacking outcomes	kuertee	201	2021-03-23	1	false
kuerteeHighSecurityRoomsAreLocked	kuertee: High security rooms are locked	kuertee	202	2021-04-22	1	false
kuerteeModPartsTrader	kuertee: Modifications parts trader	kuertee	101	2021-05-29	1	false
kuerteeMoreGenericMissions	kuertee: More generic missions	kuertee	101	2021-03-18	1	false
kuerteeNPCReactions	kuertee: NPC reactions	kuertee	216	2021-06-07	1	false
kuerteeReputationAndProfessions	kuertee: Reputations and professions	kuertee	115	2021-05-29	1	false
kuerteeShipScanner	kuertee: Ship scanner	kuertee	200	2021-03-11	1	false
kuerteeSignalLeakHunterIncreasingRange	kuertee: Signal leak hunter - increasing range	loktide / kuertee	500	2021-03-11	1	false
kuerteeStationScanner	kuertee: Station scanner	kuertee	200	2021-03-11	1	false
kuerteeSurfaceElementTargeting	kuertee: Surface element targeting	kuertee	104	2021-05-29	1	false
kuerteeTeleportFromTransporterRoom	kuertee: Teleport from transporter room	kuertee	200	2021-03-11	1	false
kuerteeUIAcceptMissionForLaterButton	kuertee UI: Accept mission for later	kuertee	201	2021-04-19	1	false
kuerteeUIActiveMissionButton	kuertee UI: Active Mission Button	kuertee	200	2021-03-11	1	false
kuerteeUIExtensionsAndHUD	kuertee UI Extensions and HUD	kuertee	211	2021-05-29	1	false
kuerteeUIFunctionalRadarTexture	kuertee UI: Functional radar texture	kuertee	100	2021-04-13	1	false
kuerteeUIResetMouseOnMenuClose	kuertee UI: Reset mouse on menu and controller	kuertee, Mycu	202	2021-04-20	1	false
kuerteeWaypointFieldsForDeployments	kuertee: Waypoint fields for deployments	kuertee	206	2021-05-29	1	false
kuerteeWearAndTear	kuertee: Wear and tear	kuertee	202	2021-04-22	1	false
LearningAllTheThings	LearnAllTheThings	iforgotmysocks	060	2018-12-12		0
Legacy_Music	Legacy Music - Extended	Winghelm	120	02 Apr. 2021		0
no_stardust	Less Stardust	Mycu	1.0	2020-04-05	1	0
lt_manager_plus	LT Manager Plus	Litauen	111	2020-03-12	1	0
MCT	Manager Credit Transfer	Matterom	140	2019-7-8	1	0
ws_2268985916	MapColors	FAIL! Chapi	115	2020-10-31		0
MineDefence Rebuilt	Anti-mine turret defence rebuilt	Scuffle Kerfuffle	103	2020-11-05	1	0
Mission Paint Mod Rewards Enhanced	Mission Paint Mod Rewards Enhanced	ZedFactor	1	2020-04-27	1	0
ws_2399395088	More Ship Rooms	Derinzed	21	2021-04-26		0
ws_1683361083	Mobile Repair Service	Assailer	132	2021-04-10		0
ws_2013772865	Mules, Supply and Warehouses Extended	MoistDreams, BHayden53, Galaxy Spam	634	2021-05-13		0
MoreGenerousMissionRewards	More generous mission rewards	Mycu	100	2021-05-15	true	false
NumberFormat	Mycu: Number Format	Mycu	1	2020-05-10		0
RebalancedSeminars	Rebalanced Seminars	Mycu	100	2020-10-30	1	false
StopDestroyingMyBoardingTarget	Stop destroying my boarding target!	Mycu	210	2021-05-05	true	false
No_Dark_Ambient	No Dark Ambient	Winghelm	400	02 Apr. 2021		0
X4 Sound Overhaul	X4 Sound Overhaul	Neloth	147	2020-02-02		0
ws_1999425584	Reactive Factions	Shuul and DeadAir	160	2020-09-25		0
ws_2463228815	Reactive Docking	Runekn	130	2021-04-20		0
RecycleShipsAndStations	RecycleShipsAndStations	iforgotmysocks	055	2018-12-08	true	false
Bane_RenameFleetShips	Bane_RenameFleetShips	BaneSorka	1.0	01-04-2019	1	0
ws_1705279348	Rise of the Ossian Raider	sco	213	2021-04-19		0
ws_2408335033	Rise of the Ossian Raider Part 2	sco	110	2021-03-29		0
ws_2065619828	Rise of the Ossian Raider VRO	Sco	212	2021-04-22		0
ws_2074074957	Go Home Drone	Shibdib	12	2020-04-26		0
ws_2053746937	Landlord	Shibdib	182	2020-05-18		0
ws_2085220886	Pay The Builder	Shibdib	102	2020-05-18		0
ws_2463118472	Reaction Force	Shibdib	207	2021-05-31		0
ws_2081316159	Training Exercise	Shibdib	130	2020-05-18		0
ws_2236431690	Ship Variation Expansion (VRO Balance)	Luca	341	2021-05-10		0
ws_2315984584	Smooth Mouse Steering	strayhound	100	2020-12-11		0
ws_2112805973	Asteroid Fade-in	SirNukes	103	2021-03-18		false
ws_2042920500	Better Target Monitor	SirNukes	200	2020-05-28		false
ws_2042920545	Extra Game Options	SirNukes	112	2021-03-23		false
ws_2042920586	SirNukes Hotkey Collection	SirNukes	106	2021-03-23		false
ws_2042901274	SirNukes Mod Support APIs	SirNukes	186	2021-04-22		false
ws_2054542372	Quiet Target Range Clicks	SirNukes	101	2020-05-01		false
ws_2042914964	Remove Dock Symbol	SirNukes	102	2020-05-06		false
sn_remove_highway_blobs	Remove Red Blobs from Super Highways	SirNukes	001	2020-4-23		false
ws_2082610969	TaterTrade	Ludsoe	115	2021-04-29		0
MoreHotkeysAdvancedTargeting	More Hotkeys: Advanced Targeting	Trajan von Olb	110	2021-06-03	1	0
ws_2463759406	Universal Defense Bounty	Sqaw (Com)	104	2021-04-29		false
ut_advanced_renaming	Advanced Renaming	UniTrader	030	2016-09-01		false
ut_advanced_renaming_user	Advanced Renaming- User Custom Expressions	UniTrader	030	2016-09-01		false
ws_2092839403	Civilian Fleets: Mimicry Extension	Vectorial1024	504	2021-06-09		0
Ventures	Ventures	iforgotmysocks	033	2019-01-13	true	false
ws_1696862840	Variety and Rebalance Overhaul	Shuul	306	2021-04-03		1
ws_1954934014	Weapon Pack	pw	118	2021-04-11		0
ws_2482456803	Weapon Variation Expansion	Luca	012	2021-05-25		0
ws_2494762346	Weapon Variation Expansion VRO	EagleDelta	110	2021-06-03		0
ws_2486524046	Improved Fleet Attack	RoverTX	100	2021-05-14		
ws_1902196111	Improved Scouts	RoverTX	109	2021-03-25		0
ws_2446450765	X4 Economy Overhaul	pw	107	2021-04-28		1
ws_2446480259	X4 Economy Overhaul VRO Patch	me	101	2021-04-05		0
ws_2055992841	X4 Fire and Smoke	pw	107	2021-03-03		0
ws_1905655811	XR ShipPack	Mac Bain	308	2021-04-21		1
ws_2042460693	XR ShipPack VRO	pw	107	2021-03-19		0
f_paintjobs	Freeq's Paintjobs	freeqstyler	120	2021-03-22		0

```

**Comment by Ocelot1210** [comment]
Thank you for reporting issue.
I have found the cause of the problem and report it as follows.

### Cause
- The "Data Exporter" was not able to properly handle duplicate data.
  - Data (KHA M Shield Generator Mk1) added by "XR ShipPack" was added to ware.xml in duplicate form, violating DB unique constraint.

### Correspondence
Modify the process so that it does not violate the unique constraint by giving priority to data added later.
(This behavior was chosen because X4 gives priority to data that is added later.)

<br>

A corresponding version of this phenomenon has been released.
Please download the latest version [here](https://github.com/Ocelot1210/X4_ComplexCalculator/releases) and let me know if this problem has been resolved.

Thank you.

**Comment by mycumycu** [comment]
This issue is fixed now.
Thank you very much!
